export type ServiceStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'

export type ServiceCategory =
  | 'IT_DEVELOPMENT'
  | 'DESIGN_GRAPHIQUE'
  | 'MARKETING_DIGITAL'
  | 'COMPTABILITE_FINANCE'
  | 'JURIDIQUE'
  | 'CONSEIL_STRATEGIE'
  | 'BATIMENT_TRAVAUX'
  | 'TRANSPORT_LOGISTIQUE'
  | 'SANTE_BIEN_ETRE'
  | 'EDUCATION_FORMATION'
  | 'AUTRE'
